### ISSUE TITLE
kube-dns endpoint metric scraping not working

### ISSUE THREAD

**Issue by LeSandeep** [newrelic/nri-prometheus#190]
## Description
This is similar to https://github.com/newrelic/nri-prometheus/issues/27
I'm trying to get prometheus metrics from `coredns` pods (not the service).

Installed using the latest helm chart like so:
```
helm upgrade --install nri-prometheus newrelic/nri-prometheus \
--namespace nri \
--set licenseKey=<redacted>\
--set cluster=<redacted>\
--set scrape_services=false \
--set scrape_endpoints=true
```
The chart installs version `2.6.0`, I manually edited the deployment to pick up the latest version: `newrelic/nri-prometheus:2.7.0` which should have the fix: https://github.com/newrelic/nri-prometheus/pull/148

I'm still seeing this in the logs:

```
time="2021-06-03T17:17:24Z" level=warning msg="fetching Prometheus metrics: http://kube-dns.kube-system.svc:9153/metrics (kube-dns)" component=Fetcher error="Get \"http://kube-dns.kube-system.svc:9153/metrics\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
```

I also tried adding the following annotations to the `coredns` pods to no avail:

```
    prometheus.io/path: metrics
    prometheus.io/port: "9153"
    prometheus.io/scrape: "true"
```

## Expected Behavior
- the coredns `endpoints` to be scraped instead of the `service`
- coredns metrics to show up in the `Metric` table in newrelic

**Comment by roobre** [comment]
Hi there,

It seems like `nri-prometheus` is not being able to contact `http://kube-dns.kube-system.svc:9153/metrics`. If you open a shell in the prometheus container, are you able to `curl` that url? Is it the expected value for it, based on the configuration and open ports for the `coredns` pods?

**Comment by paologallinaharbur** [comment]
Possibly related to https://github.com/newrelic/nri-prometheus/issues/154

**Comment by paologallinaharbur** [comment]
Closing in favour of #154, thanks again for reporting this

**Comment by paologallinaharbur** [comment]
Hello @LeSandeep, first of all sorry for the misunderstanding, the error is a bit related, but they do not 100% overlap.

I believe that setting the values you did not passed the correct argument as "config.scrape_services"

I deployed the following to my cluster:
```
helm install nri-prometheus-test newrelic/nri-prometheus \
--namespace default \
--set licenseKey=******** \
--set cluster=********\
--set config.scrape_services=false \
--set config.scrape_endpoints=true
```

And the service was no longer scraped since that option was disabled and the log you mentioned disappeared as expected. However, neither the the endpoint was scraped since the port was not present in the list (of the service or the endpoints) and currently we are checking that to make sure the pod is capable to accept that request. The check is performed [here](https://github.com/newrelic/nri-prometheus/blob/dded41760eef67a6a9990fe2c5e1aebce3083aad/internal/pkg/endpoints/kubernetes.go#L269)

 - We could add that check (that is not performed for services or to add a debug log)

Adding the port to the kube-dns service solves the issue:
```yaml
[...]
spec:
  clusterIP: 10.100.0.10
  ports:
  - name: dns
    port: 53
    protocol: UDP
    targetPort: 53
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
  - name: prom
    port: 9153
    protocol: TCP
    targetPort: 9153
[...]
```

<img width="1308" alt="Screen Shot 2021-06-17 at 11 39 45 AM" src="https://user-images.githubusercontent.com/43335750/122372139-b8d97080-cf60-11eb-937f-1995aaea1494.png">

**Comment by LeSandeep** [comment]
Ah, indeed, I was missing `config.` in the helm command's `set` argument. The docs are a bit ambiguous, but I should've just looked at `values.yaml`. Thanks for clarifying @paologallinaharbur . Also, I was able to get it to work without modifying the coredns service (i.e., adding the port), but adding the following annotations to the deployment:
```
    prometheus.io/path: metrics
    prometheus.io/port: "9153"
    prometheus.io/scrape: "true"
```
Thanks again for the help!

**Comment by paologallinaharbur** [comment]
I'll review the docs and try to improve them, thanks for raising that concern!
