### ISSUE TITLE
Scraper uses license key in place of API key

### ISSUE THREAD

**Issue by brianbao** [newrelic/nri-prometheus#32]
Hello,

I am trying to scrape Prometheus metrics and send them to the Insights dashboard via a proxy we have setup. Looking at the code and the docs for the Metrics API endpoint, it looks like the endpoint requires either the `Api-Key` or `X-Insert-Key` header [to be set](https://docs.newrelic.com/docs/data-ingest-apis/get-data-new-relic/metric-api/report-metrics-metric-api#headers-query-parameters), but this parameter in gets set as the [`license_key`](https://github.com/newrelic/nri-prometheus/blob/99f4cd98e5353356ddced8cfef397b6197c410a2/internal/cmd/scraper/scraper.go#L204) option. Should this field have been set by an API key parameter in the YAML? In my testing I was able to POST a metric by specifying both the license key and the insert/API key, but received a `400 Bad Request` when the API key was omitted.

Also when I was debugging the above issue in `verbose=True, debug=True` mode I found that the logs did not write any messages regarding emitting metrics, it seemed to silently failed -- it would be very useful to have more verbose logging around the emitter. Here's a small snippet of the logs:
```time="2019-12-02T22:36:21Z" level=debug msg="Starting fetch process..." component=fetcher
time="2019-12-02T22:36:21Z" level=debug msg="fetching URL: {http   localhost:8080 /metrics  false  }" component=Fetcher target="localhost:8080"
time="2019-12-02T22:36:21Z" level=debug msg="Finished fetch process." component=fetcher
[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}]
time="2019-12-02T22:36:21Z" level=debug msg="Starting fetch process..." component=fetcher
time="2019-12-02T22:36:21Z" level=debug msg="fetching URL: {https   localhost:443 /v1/sys/metrics  false format=prometheus }" component=Fetcher target="localhost:443"
time="2019-12-02T22:36:21Z" level=debug msg="Finished fetch process." component=fetcher
[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}]
```

**Comment by alejandrodnm** [comment]
Hi @brianbao, this project only works with the [newrelic license key](https://docs.newrelic.com/docs/integrations/prometheus-integrations/get-started/new-relic-prometheus-openmetrics-integration-kubernetes#install)

We wrap the roundtripper to add the header for sending the license key here:

https://github.com/newrelic/nri-prometheus/blob/master/internal/cmd/scraper/scraper.go#L231-L237

https://github.com/newrelic/nri-prometheus/blob/master/internal/integration/roundtripper.go#L11-L17

See as well that we delete the `X-INSERT-KEY`, that's because if both headers are present the request fails. 
 
We use the license key because the data goes through the infrastructure metrics API, which requires the license key. This is the default url for sending data to new relic:

https://github.com/newrelic/nri-prometheus/blob/master/cmd/nri-prometheus/config.go#L88

**Comment by brianbao** [comment]
Ah, I see where my misunderstanding was. The [docs](https://docs.newrelic.com/docs/data-ingest-apis/get-data-new-relic/metric-api/report-metrics-metric-api#headers-query-parameters) are for the `/metric/v1` endpoint, but the code is hitting the `/metric/v1/infra` endpoint, the former requires an insert key and the latter does not.

Thanks for the response!
