### ISSUE TITLE
Not getting data for "counter" metrics

### ISSUE THREAD

**Issue by teerexlai** [newrelic/nri-prometheus#35]
Hey, I'm using an exporter with newrelic/nri-prometheus:1.2.2 and docker. I am receiving plenty of data in metrics, however none of the metric data types are counters.

When using `verbose: true` in my config.yaml, I don't see any of the counter metrics being sent to NR in the logs. Not even the counters on the nri-prometheus/metrics endpoint.

For example, I do get data for "promhttp_metric_handler_requests_in_flight" (gauge), but I don't get data for "promhttp_metric_handler_requests_total" (counter).

I am not using any emitter or transformations. 

Any help is appreciated!

**Comment by teerexlai** [comment]
I think I was able to get the counters working properly.

Setting a time higher than 30s for `scrape_duration` in config.yaml seems to cause the issue. Mine was originally set to 60s. I tried 31s, and it also causes the issue.

This seems like a possible bug.

**Comment by douglascamata** [comment]
Thanks for the report, @teerexlai. I already have a theory about the root case and will be looking into this.

**Comment by douglascamata** [comment]
Hey @teerexlai, I figured out what is happening.

There is an internal delta calculator for the counter metrics, as only the change in their values is sent to New Relic.

This delta calculator has an expiration interval to "forget" about metrics that aren't seen after a while (otherwise the memory usage would increase forever). The expiration only happens after a certain amount of time, that we call expiration check interval. 

The default value for the expiration interval is **30 seconds**. And the default value for the expiration check interval is also **30 seconds**. Meaning that every 30 seconds the delta calculator is cleaned of keys that are older than 30 seconds.

So if the prometheus integration is running only once every 60 seconds, the delta calculator will always be empty when it runs and the counter will end up never being sent.

Unfortunately we're not yet allowing people to configure the expiration interval or check interval. Neither we're scaling them up in a smart way together with the `scrape_duration` configuration.

**Comment by douglascamata** [comment]
Feel free to open a PR if you want to contribute.
