### ISSUE TITLE
Add support for targets over DNS, like dns_sd_config in Prometheus

### ISSUE THREAD

**Issue by mkokho** [newrelic/nri-prometheus#373]
### Description
It is assumed that only one [host is behind a URL](https://github.com/newrelic/nri-prometheus/blob/f1aecab1c966759ee0caca6efb75570fe8c9805b/internal/pkg/endpoints/endpoints.go#L93) in TargetConfig struct.
However, Prometheus supports discovery of targets over DNS where one URL is resolved to multiple ip addresses.
https://prometheus.io/docs/prometheus/latest/configuration/configuration/#dns_sd_confg

**Comment by davidgit** [comment]
This issue was closed because it has been inactive for a long time despite it can be reopened at any point if you think it still relevant.

Thank you for your contribution!
Hi,

We consolidated multiple channels that were used to file Feature Requests (FRs). In the spirit of improving the visibility of FRs, we believe it's best for them to be submitted through the [New Relic Issue Tracker](https://issues.newrelic.com). This single tool will enable better aggregation of FRs and improve our ability to synthesize requests and provide better value to our users. You can see and vote for other FRs submitted by all users.

Please provide a link to this GitHub issue when submitting your feature request.

Thanks!
