### ISSUE TITLE
nri-prometheus is failing to read metrics compatible with v2 prometheus format

### ISSUE THREAD

**Issue by echoAlexey** [newrelic/nri-prometheus#45]
Hi!

We are getting error when reading metrics compatible to V2 prometheus format. 

`text format parsing error in line <line number>: second HELP line for metric name <name>`

This is probably caused by old libraries being used to parse response - from vendor.json I see deprecated https://github.com/prometheus/client_model usage dated with 2018.

Example metrics output:

```
# HELP connection_seconds Tracks time to obtain connection
# TYPE connection_seconds summary
connection_seconds{outcome="failure",quantile="0.5",} 0.0
connection_seconds{outcome="failure",quantile="0.75",} 0.0
connection_seconds{outcome="failure",quantile="0.95",} 0.0
connection_seconds{outcome="failure",quantile="0.98",} 0.0
connection_seconds{outcome="failure",quantile="0.99",} 0.0
connection_seconds{outcome="failure",quantile="0.999",} 0.0
connection_count{outcome="failure",} 0.0
connection_seconds_total{outcome="failure",} 0.0
# HELP connection_seconds Tracks time to obtain connection
# TYPE connection_seconds summary
connection_seconds{outcome="success",quantile="0.5",} 0.0
connection_seconds{outcome="success",quantile="0.75",} 0.0
connection_seconds{outcome="success",quantile="0.95",} 0.0
connection_seconds{outcome="success",quantile="0.98",} 0.0
connection_seconds{outcome="success",quantile="0.99",} 0.0
connection_seconds{outcome="success",quantile="0.999",} 0.0
connection_count{outcome="success",} 333.0
connection_seconds_total{outcome="success",} 0.05
```

**Comment by fieldju** [comment]
I too am noticing that summaries are not showing up in New Relic insights using this integration.
This is a huge blocker to rolling this out.

**Comment by paologallinaharbur** [comment]
From the [docs](https://docs.newrelic.com/docs/integrations/prometheus-integrations/get-started/send-prometheus-metric-data-new-relic/#OpenMetrics) 
```
This integration supports Prometheus protocol version 2 and Kubernetes versions 1.9 or higher.
```

**Comment by davidbrota** [comment]
Hi @echoAlexey 

The problem here lies in the second HELP token. The [Prometheus documentation](https://prometheus.io/docs/instrumenting/exposition_formats/#comments-help-text-and-type-information) states that "Only one HELP line may exist for any given metric name."

Furthermore, the `github.com/prometheus/client_model` library, even the latest version, enforces that restriction [here](https://github.com/prometheus/common/blob/b4304c504af1cf993f7b6873c5455e0ac51726a7/expfmt/text_parse.go#L495)

If you remove the second help token, along with the second type token, then the integration will scrape the data correctly.
